import { mutation } from "./_generated/server";

// Clear all existing products
export const clearProducts = mutation({
  handler: async (ctx) => {
    const products = await ctx.db.query("products").collect();
    for (const product of products) {
      await ctx.db.delete(product._id);
    }
    return { success: true, deletedCount: products.length };
  },
});

// Seed new products
export const seed = mutation({
  handler: async (ctx) => {
    const demoProducts = [
      // Holiday Drinks
      {
        name: "Winter Spice Mocha",
        description: "Rich mocha topped with whipped cream and a cinnamon stick. Warm spices of cinnamon and nutmeg create the perfect winter comfort drink.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1514066558159-fc8c737ef259?w=800&q=80",
        origin: "Brazil",
        roastType: "Dark",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Peppermint Velvet Cold Brew",
        description: "Smooth cold brew topped with velvety peppermint cream and candy cane pieces. A refreshing holiday favorite that combines cool mint with rich coffee flavors.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&q=80",
        origin: "Colombia",
        roastType: "Medium",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Gingerbread Latte Bliss",
        description: "Creamy latte infused with warm gingerbread spices and topped with whipped cream and a gingerbread cookie. Captures the cozy flavors of freshly baked gingerbread.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1514066558159-fc8c737ef259?w=800&q=80",
        origin: "Ethiopia",
        roastType: "Medium",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: false,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Italian Tiramisu Latte",
        description: "Espresso-based latte with mascarpone cream and cocoa dusting. Inspired by the classic Italian dessert, layered with rich coffee and sweet cream.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800&q=80",
        origin: "Italy",
        roastType: "Dark",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Mexican Spiced Chocolate Mocha",
        description: "Rich chocolate mocha infused with traditional Mexican spices including cinnamon and a hint of chili. A bold and warming drink inspired by Mexican hot chocolate traditions.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800&q=80",
        origin: "Mexico",
        roastType: "Dark",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Matcha Snow Latte",
        description: "Japanese matcha green tea latte with steamed milk and a snow-like foam topping. Earthy, creamy, and beautifully balanced.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=800&q=80",
        origin: "Japan",
        roastType: "Light",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Turkish Delight Mocha",
        description: "Exotic mocha inspired by traditional Turkish coffee, featuring notes of rosewater and topped with whipped cream and cocoa powder. A luxurious Middle Eastern-inspired treat.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&q=80",
        origin: "Turkey",
        roastType: "Dark",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Parisian Chestnut Praline Latte",
        description: "Creamy latte with roasted chestnut and praline flavors, topped with whipped cream and crushed chestnuts. A French-inspired winter delicacy.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=800&q=80",
        origin: "France",
        roastType: "Medium",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },

      // International Coffees
      {
        name: "Korean Whipped Coffee (Dalgona)",
        description: "A viral South Korean drink featuring fluffy whipped coffee over milk for a velvety, frothy treat.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1587080413959-06b859fb107d?w=800&q=80",
        origin: "South Korea",
        roastType: "Medium",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Turkish Coffee",
        description: "Finely ground coffee simmered (not filtered) in a small cezve pot, yielding an intense, full-bodied flavor.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1610889556528-9a770e32642f?w=800&q=80",
        origin: "Turkey",
        roastType: "Dark",
        dietaryProfile: {
          nonDairy: true,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Mexican Coffee (Café de Olla)",
        description: "Traditional clay-pot coffee brewed with cinnamon sticks and piloncillo (raw cane sugar) for a spiced, rustic flavor.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80",
        origin: "Mexico",
        roastType: "Medium",
        dietaryProfile: {
          nonDairy: true,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Café con Leche",
        description: "Spanish and Latin American classic of equal parts espresso and steamed milk — smooth, warm, and comforting.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&q=80",
        origin: "Spain",
        roastType: "Medium",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Italian Coffee Cocktail",
        description: "A rich espresso mixed with a touch of coffee liqueur and topped with cream for a luxurious after-dinner drink.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1514481538271-cf9f99627ab4?w=800&q=80",
        origin: "Italy",
        roastType: "Dark",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Cuban Cafecito",
        description: "Sweet, strong espresso whisked with demerara sugar to create a rich, caramel-like foam.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1497515114629-f71d768fd07c?w=800&q=80",
        origin: "Cuba",
        roastType: "Dark",
        dietaryProfile: {
          nonDairy: true,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Moroccan Spiced Coffee",
        description: "Fragrant and flavorful coffee infused with warm spices like cardamom, cloves, and nutmeg.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
        origin: "Morocco",
        roastType: "Medium",
        dietaryProfile: {
          nonDairy: true,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "New Orleans Coffee",
        description: "Deep-roasted coffee blended with chicory root for a bold, slightly smoky flavor.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&q=80",
        origin: "United States",
        roastType: "Dark",
        dietaryProfile: {
          nonDairy: true,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Delhi-Styled Cold Coffee",
        description: "Indian café favorite made by blending instant coffee, milk, ice, and cocoa for a thick, milkshake-like texture.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=800&q=80",
        origin: "India",
        roastType: "Medium",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Hong Kong YuanYang",
        description: "Unique East-West blend combining Hong Kong milk tea with brewed coffee — creamy, robust, and energizing.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&q=80",
        origin: "Hong Kong",
        roastType: "Medium",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Yemeni Ginger Coffee (Qishr)",
        description: "A traditional brew made from lightly roasted coffee husks with ginger and cinnamon — aromatic and soothing.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1521302200778-33500795e128?w=800&q=80",
        origin: "Yemen",
        roastType: "Light",
        dietaryProfile: {
          nonDairy: true,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Irish Coffee Cocktail",
        description: "Hot brewed coffee mixed with Irish whiskey, brown sugar, and a layer of lightly whipped cream.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=800&q=80",
        origin: "Ireland",
        roastType: "Medium",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Italia Affogato",
        description: "A scoop of vanilla gelato 'drowned' in hot espresso — simple, sweet, and perfectly Italian.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&q=80",
        origin: "Italy",
        roastType: "Dark",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "French Café au Lait",
        description: "Classic French breakfast drink made with equal parts strong coffee and steamed milk.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1511537190424-bbbab87ac5eb?w=800&q=80",
        origin: "France",
        roastType: "Medium",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Swedish Egg Coffee",
        description: "A Scandinavian method that mixes ground coffee with a raw egg before brewing, producing an exceptionally smooth cup.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80",
        origin: "Sweden",
        roastType: "Light",
        dietaryProfile: {
          nonDairy: true,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Italian Cappuccino",
        description: "Espresso topped with steamed milk and a thick layer of foam — balanced, aromatic, and best enjoyed fresh.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800&q=80",
        origin: "Italy",
        roastType: "Dark",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: true,
        },
        inStock: true,
        createdAt: Date.now(),
      },

      // Pastries & Sweets
      {
        name: "Butter Croissant",
        description: "A French classic made from laminated dough and real butter, baked until golden for a crisp, airy texture.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800&q=80",
        origin: "France",
        roastType: "Light",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: false,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Shortbread Cookies",
        description: "A traditional Scottish treat made with butter, sugar, and flour for a delicate, melt-in-your-mouth bite.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&q=80",
        origin: "Scotland",
        roastType: "Light",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: false,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Chocolate Chip Cookie",
        description: "A timeless favorite with soft centers, crisp edges, and rich chocolate morsels in every bite.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&q=80",
        origin: "United States",
        roastType: "Medium",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: false,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Blueberry Muffin",
        description: "Soft, bakery-style muffin packed with juicy blueberries and a hint of vanilla.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=800&q=80",
        origin: "United States",
        roastType: "Light",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: false,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Carrot Cake",
        description: "Moist and warmly spiced with cinnamon and nutmeg, layered with smooth cream-cheese frosting.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1621303837174-89787a7d4729?w=800&q=80",
        origin: "United States",
        roastType: "Medium",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: false,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Danish Pastry",
        description: "Buttery, layered dough filled with fruit jam or cream cheese, finished with a sweet glaze.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80",
        origin: "Denmark",
        roastType: "Light",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: false,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Chocolate Croissant (Pain au Chocolat)",
        description: "Originating in France, this pastry folds dark chocolate inside buttery croissant dough.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1530610476181-d83430b64dcd?w=800&q=80",
        origin: "France",
        roastType: "Dark",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: false,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Banana Bread",
        description: "Moist loaf made from ripe bananas, brown sugar, and warm spices — a comforting classic read.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800&q=80",
        origin: "United States",
        roastType: "Medium",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: false,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Oatmeal Raisin Cookie",
        description: "A hearty cookie combining oats, plump raisins, brown sugar, and a touch of spice.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1590080876351-cd8b6c992e3a?w=800&q=80",
        origin: "United States",
        roastType: "Light",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: false,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Chocolate Chip Muffin",
        description: "A fluffy vanilla muffin studded with chocolate chips, perfect for a quick sweet bite.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1607920591413-4ec007e70023?w=800&q=80",
        origin: "United States",
        roastType: "Medium",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: false,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Cheesecake Slice",
        description: "Smooth cream cheese filling on a buttery graham-cracker crust, finished with fresh fruit or cream.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1533134486753-c833f0ed4866?w=800&q=80",
        origin: "United States",
        roastType: "Light",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: false,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Cinnamon Roll",
        description: "Swirled with brown sugar and cinnamon, baked soft and topped with creamy vanilla icing.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1509365390275-f5657f4c3a67?w=800&q=80",
        origin: "Sweden",
        roastType: "Medium",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: false,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Almond Croissant",
        description: "Flaky pastry filled with almond frangipane and topped with toasted almonds and powdered sugar.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1598751116350-967697e0d72a?w=800&q=80",
        origin: "France",
        roastType: "Light",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: false,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Lemon Pound Cake",
        description: "Dense yet tender, infused with fresh lemon zest and drizzled with a tangy glaze.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1519915212116-7cfef71f1d3e?w=800&q=80",
        origin: "United Kingdom",
        roastType: "Light",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: false,
        },
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Scone (Plain / Raisin / Cranberry)",
        description: "Buttery British-style scones, lightly sweet and crumbly — best served warm with jam or cream.",
        price: 699,
        imageUrl: "https://images.unsplash.com/photo-1580386693971-372cb7fb4589?w=800&q=80",
        origin: "United Kingdom",
        roastType: "Light",
        dietaryProfile: {
          nonDairy: false,
          glutenFree: false,
        },
        inStock: true,
        createdAt: Date.now(),
      },
    ];

    for (const product of demoProducts) {
      await ctx.db.insert("products", product);
    }

    return { success: true, count: demoProducts.length };
  },
});